### PR TITLE
bad regex

### PR DESCRIPTION
**Pull request by austinpray**

### CODE REVIEW

**Comment by ridhoq** [comment]
This doesn't match correctly. Confirmed for bad. It doesn't match more than one t at the end of the string.

/s+h+e+i+t/ should do the trick.

If you could make that case insensitive, you would be not bad.

**Comment by austinpray** [comment]
screenshot 2015-04-17 10 19 00

**Comment by austinpray** [comment]
dawg it works try again

**Comment by ridhoq** [comment]
Try with multiple t's?

**Comment by austinpray** [comment]
Pull latest update it works

**Comment by ridhoq** [comment]
U mongoloid I want it to pick up a string like this: "sssshhhheeeeeiiiiittttttt". That is not matched with your regex.

**Pull request closed without merging**
